apps:
  # a small web app so we can view our xbahn data
  test_app:
    home: test_app
    enabled: true

data:
  # data handler for xbahn messages sent to xbahn path "test" on
  # xbahn plugin "xbahn_server"
  - type: xbahn_server.test
    handlers:
      - type: store
        container: list
        limit: 10

plugins:
  # xbahn plugin using zmq sub socket to listen for incoming
  # messages
  - type: xbahn
    name: xbahn_server
    connections:
      - name: main
        bind: zmq://0.0.0.0:7061/sub/test

  # web server
  - type: flask
    name: http
    bind: 0.0.0.0:7060
    debug: true
    server: uwsgi
    async: thread
    routes:
      /: test_app->index

logging:
  version: 1
  formatters:
    simple:
      format: '%(asctime)s - %(name)s - %(levelname)s: %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout
  loggers:
    xbahn:
      level: DEBUG
      handlers:
        - console
    vodka:
      level: DEBUG
      handlers:
        - console
